### ISSUE TITLE
Player doesn't start on old android web browsers in webview when activated google ima.

### ISSUE THREAD

**Issue by mahmutbayri** [hola/hola_player#10]
Hi,

Old Android browsers are using by a few people, but webview engines in android applications use old  android browser in version <= 4.4.2 . In these devices when a user click on the player, player doesn't do anything. If the player starts without google ima, the player plays as expected.

I use  function at below to detect this browsers.
```
    var isAndroidBrowser = function() {
       var navU = navigator.userAgent;

       // Android Mobile
       var isAndroidMobile = navU.indexOf('Android') > -1 && navU.indexOf('Mozilla/5.0') > -1 && navU.indexOf('AppleWebKit') > -1;

       // Apple webkit
       var regExAppleWebKit = new RegExp(/AppleWebKit\/([\d.]+)/);
       var resultAppleWebKitRegEx = regExAppleWebKit.exec(navU);
       var appleWebKitVersion = (resultAppleWebKitRegEx === null ? null : parseFloat(regExAppleWebKit.exec(navU)[1]));

       // Chrome
       var regExChrome = new RegExp(/Chrome\/([\d.]+)/);
       var resultChromeRegEx = regExChrome.exec(navU);
       var chromeVersion = (resultChromeRegEx === null ? null : parseFloat(regExChrome.exec(navU)[1]));

       // Native Android Browser
       return isAndroidMobile && (appleWebKitVersion !== null && appleWebKitVersion < 537) || (chromeVersion !== null && chromeVersion < 37);
   };

   var playerConfigs = {}; // some configs

   if (!isAndroidBrowser()) {
       playerConfigs.ads = {
           adsUrl: "url",
       };
   }

   hola_player(playerConfigs); //
```

I guess google ima sdk or videojs-ima has a bug. Many people uses devices with <= 4.4.2 android os, in applications  use webview videojs-ima doesn't working well.  Do you have any suggestion for this situation?

**Comment by akashta** [comment]
Hi, 
I'm trying to reproduce this with android emulator. It would be very helpful if you could give some more info:
- page URL. Is it reproducible on the following page? http://jsbin.com/bilahoq/1/edit?html,output
- exact user agent string for such device
- browser console output 
- error messages, screenshot, etc.

**Comment by mahmutbayri** [comment]
Hi,


This is user agent of the test device:
User agent is Mozilla/5.0 (Linux; Android 4.4.2; LG-D802TR Build/KOT49I.D802TR20c) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36

This is my test page: http://www.mynet.com/tv/hola_player_test.html

You can see the problem run the test page in a WebView container.

**Comment by akashta** [comment]
Hi,
I've tried to reproduce this issue on different real devices and emulator, but with no luck. The closest I've found is Android 4.4.2 emulator with a user agent:
`Mozilla/5.0 (Linux; Android 4.4.2; Android SDK built for x86 Build/KK) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36`
The emulator has a bug with displaying video (black screen instead of the video, but audio plays fine) which is not related to Hola player and effects plain mp4 video as well.
Your test page works on this emulator. There is an ad and the main video after it (actually only sound, because of the emulator bug).

Could the described issue be related only to your test device?
Do you see an ad but the video after it doesn't work, or the player doesn't respond to a click and doesn't start an ad?

**Comment by mahmutbayri** [comment]
Hi,

The player doesn't respond to a click. When i click to player device fire touch event, but doesn't anything happen.

I will try to send a video.

**Comment by mahmutbayri** [comment]
Screencast -> https://drive.google.com/file/d/0B1C2r2ovnkvQUmJRSGNhOFQzWXM/view?usp=sharing

**Comment by akashta** [comment]
Could you please share this app sources?

**Comment by mahmutbayri** [comment]
Hi,
Yes, it is here -> https://github.com/erayasan/android-webview-browser

**Comment by akashta** [comment]
Thanks for the app. Now I can reproduce the issue.

**Comment by akashta** [comment]
Hi, 
For some reason video element ignores click event that come from google ima iframe.
I made a workaround to fix the issue. To activate it you should init the player with `ads.hideAdContainer=true` option. Player will hide an ad container and show it only after user clicks on the video.
