### ISSUE TITLE
Error: Cannot find module 'dashjs/dist/dash.mediaplayer.debug.js'

### ISSUE THREAD

**Issue by afuggini** [hola/hola_player#13]
Hi,

After running `npm install`, when building with `grunt` I get the following error while building:

```
Running "browserify:dist" (browserify) task
>> Error: Cannot find module 'dashjs/dist/dash.mediaplayer.debug.js' from '/*myFolder*/HolaPlayer/src'
```

I could make it work by cloning `https://github.com/Dash-Industry-Forum/dash.js` into the `node_modules` folder.

When I run `npm install --save dashjs` Dash module is added within `node_modules/@hola.org/dashjs`.

Am I doing anything wrong? How do I build it correctly?

Thanks.

**Comment by akashta** [comment]
Hi,
Are you trying to build the latest version? There was a similar bug, but it was fixed in 1.0.24.
I've just cloned `hola_player` to the new directory and `npm install && grunt` works for me.
