### ISSUE TITLE
Non-linear Ads with VMAP Does Not Work

### ISSUE THREAD

**Issue by erendemir** [hola/hola_player#14]
When you put directly non-linear ad, it does work. However if you put non linear ad inside a VMAP with timeoffset and provide this vmap file to player, it does not show the ads.

I tried both google's test player and, another open source videojs player, they work perfectly. However it does not work with Hola Player.

Here is the google player test url with valid VMAP file : https://goo.gl/fGh2TL

**Comment by mahmutbayri** [comment]
Test page is here -> http://www.mynet.com/tv/hola/audioreco_single_vmap.php?ads=https://ads.audioreco.com/samples/ima-overlay-mezosfer.xml

I have solved the problem on our old player based on videojs.

https://drive.google.com/open?id=0B_pF64o1j2FEcldMbmtQSnY2SDA

Thanks.

**Comment by erendemir** [comment]
Thanks for your answer @mahmutbayri this is great!

Do you know how we can solve this programmaticly ?  Do you have any idea which javascript code causes this ?

**Comment by mahmutbayri** [comment]
My solution was overriding videojs-ima libs.

I have added this code
```
    if(this.currentAd != null && !this.currentAd.isLinear()) {
        this.adContainerDiv.style.display = 'block';
     }
```
before https://github.com/hola/videojs-ima/blob/master/src/videojs.ima.js#L507 line.

I didn't test with hola player.

**Comment by akashta** [comment]
I've found the reason, will fix in the next version.

**Comment by akashta** [comment]
Fixed in 1.0.59

**Comment by mahmutbayri** [comment]
Thanks.
When it will be available in cdn? In http://player2.h-cdn.com/hola_player.js?customer=mynet file is still using 1.0.58 version.

When I checked http://player2.h-cdn.com/hola_player.js?customer=demo file, i saw the version was changed to 1.0.59.

**Comment by akashta** [comment]
I've updated the version for your account. Now it's 1.0.59. It can be configured on Hola CDN Control Panel.
