### ISSUE TITLE
Control player via JavaScript?

### ISSUE THREAD

**Issue by reevester** [hola/hola_player#16]
Hey,

1. How do I control i.e. stop the player using a JavaScript event?

Use case: I am opening the player in a floating div and I want to stop playback when someone clicks the CLOSE button on the floating div.

2. When dealing with VAST/VPAID ads, when I click on REPLAY, it does not replay the ad. Any suggestions on what the issue could be?

Sample: http://www.adcanvass.com/testing/slider/git.html

**Comment by akashta** [comment]
Hi,

1. hola_player() function returns object with `vjs` field. You can use it to control the player. Something like:
```
    var pl = window.hola_player();
    // and later
    pl.vjs.pause()
```

2. Ads are shown only once. It's original behaviour of google videojs-ima plugin: https://googleads.github.io/videojs-ima/examples/simple/  
If you want to overcome it, I suppose that the best way is to recreate the player after replay was clicked.

**Comment by reevester** [comment]
Hey @akashta 

Thanks a ton! I sincerely assist the help here....!

Could you assist me with how to recreate the player when the replay icon is clicked or when the video has stopped playing?

**Comment by akashta** [comment]
I've found a better way, without recreating a player. You can just call `vjs.ima.playAd(adTagUrl)` after replay.
Here is an example I've created for you:
http://jsbin.com/safesamexi/edit?html,console,output

**Comment by reevester** [comment]
Hey @akashta you are an angel in disguise man! 

One last query, do you know how to get this working with a VAST XML rather than a VAST URL?

**Comment by akashta** [comment]
> One last query, do you know how to get this working with a VAST XML rather than a VAST URL?

You can try to use `adsResponse` option instead of `adTagUrl` and call `playAd` function without params.
https://github.com/hola/videojs-ima#additional-settings
