### ISSUE TITLE
Self hosting ios Can not load skin

### ISSUE THREAD

**Issue by ppoot** [hola/hola_player#17]
hls stream
Self hosting ios Can't load skin 
Can't fast forward and full screen

**Comment by ppoot** [comment]
It can
But set the rate after the failure
data-setup='{ "playbackRates": [0.5, 1, 1.5, 2] }'

**Comment by norlin** [comment]
Hi! 
Could you please make an example? (e.g., on jsbin.com, or any other test page)

**Comment by ppoot** [comment]
<video preload="none" data-setup='{ "playbackRates": [0.5, 1, 1.5, 2] }' class="video-js vjs-default-skin" width="640" height="360" controls>
    <source src="http://player.h-cdn.org/static/hls/cdn2/master.m3u8" type="application/x-mpegurl">

Add to
`data-setup='{ "playbackRates": [0.5, 1, 1.5, 2] }'`

There will be problems in ios

**Comment by norlin** [comment]
When I'm using the `playbackRates` option, the video plays good in iOS, as I see.

Which problems do you mean?
Please make the example page or add reproducing steps for your issue.
Also please describe the expected results and actual results – it will be very helpful for investigation of your issue.

**Comment by ppoot** [comment]
example
http://165.227.0.135/2222.html

ios img
https://imgur.com/a/UmmU9

Unable to control video

**Comment by ppoot** [comment]
and  hola-player-1.0.65.zip   hola-player-1.0.64
on opera Browser Not working
