### ISSUE TITLE
Player doesnt pause Ads.

### ISSUE THREAD

**Issue by kadircanerergun** [hola/hola_player#18]
I can pause player without ads but when player has ads i can not pause it. I tried the problem on your demo page. You can see it below. 

https://i.hizliresim.com/jWnvXn.png 

Demo page: http://hola.github.io/examples/cdn/#hola_player_ima

**Comment by akashta** [comment]
Hi,
`vjs.pause()` and `vjs.play()` functions control only the main video, but not the ad. To pause/play the ad you should use `vjs.ima.pauseAd()` and `vjs.ima.resumeAd()`

**Comment by norlin** [comment]
Hi, @kadircanerergun!

We have improved this behavior (v1.0.69), you can check it on the same examples page – now it should work as you expected.
