### ISSUE TITLE
videojs Plugin does it work?

### ISSUE THREAD

**Issue by ppoot** [hola/hola_player#20]
https://github.com/ctd1500/videojs-hotkeys

How to use it?

**Comment by ppoot** [comment]
hope hotkeys integrated in the next version.

**Comment by tonykor** [comment]
Is is possible to use videojs plugins with this player?

**Comment by akashta** [comment]
Yes, it's possible, just need to init hola_player as follows:
```
window.hola_player({
  videojs_options: {
    plugins: {
      <plugin>: <plugin conf>
    }
  }
});
```
example: http://jsbin.com/bucisehojo/edit?html,output

**Comment by ppoot** [comment]
thank you very much, but It has a bug.
It can't Double-clicking with the mouse toggles fullscreen off and on

**Comment by akashta** [comment]
Hola Player toggles fullscreen mode by double-click by default, without plugins. 
`videojs-hotkeys` does the same, so on double-click player turns fullscreen on and immediately off.
You can fix it by disabling `videojs-hotkeys` fullscreen feature:
`enableFullscreen: false`
