### ISSUE TITLE
quality switcher?

### ISSUE THREAD

**Issue by tonykor** [hola/hola_player#21]
Is there an ability to switch between quality HD/SD?

**Comment by akashta** [comment]
Hi, yes, here is an example: http://jsbin.com/sineqetuvu/edit?html,output

**Comment by tonykor** [comment]
it's good, thanks for support!

**Comment by tonykor** [comment]
Hello once again, can i know is it possible to select default source dynamically for example depending on users screen size something like this like 

```
        var width = window.screen.width;
        var height = window.screen.height;
        var defaultQualityLabel="720";
        if (width<=500 || height<=500){
            defaultQualityLabel="360";
        }

        player.setDefaultQuality(defaultQualityLabel);

```
or when initializing player. thanks

**Comment by akashta** [comment]
yes, it's possible. You can just add `default` attribute for `source` element

**Comment by tonykor** [comment]
i have 2 quality types 360p and 720p (default), i'm currently doing this such way, but i think it's not a good idea.

```        
            var width = window.screen.width;
            var height = window.screen.height;
            var defaultQualityLabel="720p";
            if (width<=500 || height<=500){
                defaultQualityLabel="360p";
                var sources=document.getElementsByTagName("source");
                if (sources[1].getAttribute("label") == defaultQualityLabel){
                    sources[0].removeAttribute('default');
                    sources[1].setAttribute('default', '');
                }
            }
```

**Comment by akashta** [comment]
I think that in this case better to pass sources array as player params:
```
        window.hola_player({
          sources: [
            {src: 'http://player.h-cdn.org/static/mp4/tears_of_steel_360p_MP4.mp4', type:'video/mp4', label: '360p', default: true},
            {src: 'http://player.h-cdn.org/static/mp4/tears_of_steel_1080p_MP4.mp4', type:'video/mp4', label: '1080p'}
          ],
        });
```

**Comment by tonykor** [comment]
Hello, seems like quality switcher not working on ios 11.0.3

**Comment by akashta** [comment]
Hi,
It does not work only on iOS 11.0.3? Could you please give a link to the test page?

**Comment by tonykor** [comment]
I have tried the demo you have provided and it's working good. I don't know may be there is a problems with my code. If the video is running and i'm changing the quality it goes good, but when i stop the video and then change the quality all the player area is black. I just see in html that the video player has a new source. Unfortunately i can not provide with a sample as it's not a production version. Thanks

**Comment by tonykor** [comment]
It's working now on the latest version of the player.
