### ISSUE TITLE
How to make player fluid with wordpress plugin

### ISSUE THREAD

**Issue by jinyus** [hola/hola_player#22]
Hi, I have a div that I want the player to fit in, I usually use 100% for width and height but the wordpress plugin only supports fixed dimensions (1280x720) Is there any way to make the player fit the width of the div that it is in? or Can you guys update the plugin to support percentage for dimensions?

**Comment by jinyus** [comment]
I am using the wordpress plugin which generates a shortcode so there is no where to put {videojs_options: {fluid: true}}

Here is the shortcode that it generates:
[hvp-video url="http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_10mb.mp4" controls="true" autoplay="false" loop="false" muted="false" ytcontrol="false"][/hvp-video]

**Comment by akashta** [comment]
Try to add class="vjs-fluid" attribute to the shortcode.

**Comment by jinyus** [comment]
Thanks a lot, it works!

**Comment by jinyus** [comment]
Found another problem it does work well with potrait videos (400x720), it scales the video dimensions...so it stretches the width of the video to 1280 but I would rather black bars at the sides. Is there anyway to fix this?

**Comment by jinyus** [comment]
I would like it to ignore the aspect ratio of the video

**Comment by akashta** [comment]
You can also try to use `vjs-16-9` or `vjs-4-3` instead of `vjs-fluid`.

**Comment by rufcut** [comment]
I have the exact problem, when I tried vjs-4-3 the video fit in the player but then it is not fluid anymore so it doesn't take up the full width of the div

**Comment by jinyus** [comment]
Here are some examples:

This is what I am trying to achieve: http://sprintking-cf.stackstaging.com/2017/09/16/portrait-test/
This is what I get with hola player: http://sprintking-cf.stackstaging.com/2017/09/16/hola-player-potrait-test/

Is there anyway to achive it with hola player? I tried vjs-4-3 but the player doesn't full up the div, so it doesn't fit on mobile devices

**Comment by akashta** [comment]
Have you tried `vjs-16-9`? I've added it via dev tools and it looks good: https://prnt.sc/gmhgka

**Comment by jinyus** [comment]
Weird, I tried this before and it didn't work but now it does. Maybe I made a typo in the shortcode. Thanks again
