### ISSUE TITLE
Passing XML to the player & detecting no ad event

### ISSUE THREAD

**Issue by reevester** [hola/hola_player#23]
Hey there,

I am trying to pass an XML value to the player by getting the XML of the ad tag using:

```
function getStatus(url) 
    {
		console.log('vSlider: Inside GetStatus function!');
		//var pl = window.hola_player();
		var x = new XMLHttpRequest();
		var NoAdToPlay = 1;
		x.open("GET", adTagUrl, true);
		x.onreadystatechange = function () {
		  if (x.readyState == 4 && x.status == 200)
		  {
			NoAdToPlay = 0;
			doc = x.responseXML;
		  }
		  if (NoAdToPlay == 1)
		  {
			  console.log('vSlider: The player did not find an ad to play! Closing player and cleaning up resources');
			  slideOutVideoPlayer();
		  }
		  //console.log('vSlider: The response from the server: ' + x.status);	
		};
		x.send(null);
    }

```

I then pass the XML variable doc to the player as shown:

```
var pl = window.hola_player({
			poster: loadURL + '/vslider/poster.png',
			ads: {
			  //adTagUrl: adTagUrl,
			  adsResponse: doc,
			},
			settings: {
			  quality: true,
			},
		  });
```

But it never ends up playing the video. How do I need to call playAd()?

**Secondly**, is it possible to detect a no ad found event so I can not show the player altogether

**Comment by akashta** [comment]
Hi,
1. Try to use `responseText` instead of `responseXML`
2. We have `nopreroll` player event, it may help

**Comment by reevester** [comment]
I still get the error 'Missing Ad Tag' :(

**Comment by akashta** [comment]
Please provide a test page where I can reproduce the issue

**Comment by reevester** [comment]
http://reeveluiz.com/slider_testing/index.html

**Comment by reevester** [comment]
Any luck bro? I really appreciate all the help!

**Comment by akashta** [comment]
Something is wrong with this line: `pl.playAd(adsResponse);`
`adsResponse` variable is not defined but you are trying yo use it.

**Comment by reevester** [comment]
I just passed the variable that holds the text string output (check the modified sample above), same issue. No ad tag issue in console...

**Comment by akashta** [comment]
I'm sorry, but all I can do is give an example of using `adsResponse` param: http://jsbin.com/rugitazoga/edit?html,output
