### ISSUE TITLE
Adding buttons

### ISSUE THREAD

**Issue by tonykor** [hola/hola_player#24]
Hello,

could you please write the correct way of adding custom buttons with tooltips to control bar. I'm trying to implement this plugin https://github.com/manelpb/videojs-brand

Thanks.

**Comment by akashta** [comment]
Hi,
You don't need to use any plugins to add logo to the control bar. It's a built-in feature of Hola Player. Here is an example: https://github.com/hola/hola_player/blob/master/examples/watermark.html

**Comment by tonykor** [comment]
The problem is that when i click the logo in the control bar generated by built in plugin, it opens the new page over the player but the player is not paused.

**Comment by tonykor** [comment]
is it also possible to add a tooltip to this logo like on other controls

**Comment by akashta** [comment]
Added in version 1.0.100
