### ISSUE TITLE
Share button, embed code.

### ISSUE THREAD

**Issue by tonykor** [hola/hola_player#25]
Hello, could you please extend share button. So that it was possible to specify player embed code.

Thanks

**Comment by akashta** [comment]
You can specify share.url param:
`share: {url: '<your url>'}`

**Comment by tonykor** [comment]
It's not an embed code, an embed code is what the user can put on his website to show the player directly for his visitors. As a rule it's an iframe code with a player with current movie.

**Comment by akashta** [comment]
There is a "Copy embed code" item in the context menu. It will appear if player initialized with `embed_code` option

**Comment by tonykor** [comment]
Thanks
