### ISSUE TITLE
Audio muted on iOS devices

### ISSUE THREAD

**Issue by jinyus** [hola/hola_player#28]
Some of my users on iOS devices are complaining that there is no sound for them. They are saying that the video starts on mute and the audio icon doesn't show on iphones/ipads. Muted is set to false and it works on my android devices. Unfortunately I don't have an iPhone to test this. 

Could anyone test the link below with an iOS device or investigate this problem?

Here is a sample: http://sprintking-cf.stackstaging.com/2017/09/18/hola-test-vjs-16-9/

**Comment by akashta** [comment]
Fixed in version 1.0.100. Now there should be a mute button on iOS, if mute is supported.
