### ISSUE TITLE
Missing crucial JS and CSS files

### ISSUE THREAD

**Issue by crmey** [hola/hola_player#3]
The project is missing crucial JS and CSS files. The paths in hola_player.js are wrong and thus they don't load the dependencies. Overall, if someone tries to download or clone the repository and use it locally, it just doesn't work.

Please include all the dependencies like video.js and css files required for Hola player to work.

**Comment by bahaa-aidi** [comment]
Hi, here's a working demo: http://jsbin.com/toposo this uses the hola_player.js hosted on jsDelivr, no additional scripts or css necessary.

to use locally you can clone this repository and build it like this:
```
git clone https://github.com/hola/hola_player.git
cd hola_player
npm install
grunt
```
the compiled results will be in the `dist/` directory, after you build it you can run any of the examples in the `examples/` directory.

you can fetch the latest version with compiled player like this: `npm install @hola.org/hola_player` or fetch a tarball like this: `npm pack @hola.org/hola_player`

**Comment by crmey** [comment]
Wouldn't it be better if there is a version/branch which users can download and use directly in their projects? Sometimes, you don't want hosted libraries like jsDelivr and want to include all the files locally in the project. Also, not everybody has Node.js running on their server so just providing the necessary JS and CSS directly would be a good idea. 

Just my 2 cents.

**Comment by bahaa-aidi** [comment]
OK, I'm convinced, we'll start adding compiled scripts to our releases on GitHub.
I'll probably set this up on Sunday

**Comment by crmey** [comment]
Thank you.
