### ISSUE TITLE
Thumbnails not moving

### ISSUE THREAD

**Issue by shuaaaa** [hola/hola_player#30]
I tried the basic html using the thumbnails plugin and I can't seem to get the thumbnails to move with the progress bar on hover. 

example: www.nudality.com (SFW) 

I just used this in the index.html

```
<!DOCTYPE html>
<html>
<head>
  <script src="/hola_player.js"></script>
</head>
<body>
  <div><h1>Video tag with Hola Player - playing MP4 without HolaCDN</h1></div>
  <video class="video-js vjs-default-skin"  width="640" height="360" controls>
    <source src="/video.mp4" type="video/mp4">
  </video>
<script>
  (function(){
    window.hola_player({thumbnails: {vtt: '/thumbs.vtt'}});
  })();
</script>
</body>
</html>

```

**Comment by akashta** [comment]
Here is a working example: http://hola.github.io/examples/cdn/#hola_player_vtt_thumb
I tried to check nudality.com but it doesn't work for me:
`mechbunnydemo.com/media/thumbs/5/7/3/9/8/57398e62868b88.67618522.mp4/vtt_012.jpg Failed to load resource: the server responded with a status of 403 (Forbidden)`

**Comment by shuaaaa** [comment]
Hi Sorry. I just took the video and .vtt file from them because I use the same kind .

Try the site again, I put the images onto the nudity server. 

Where I'm confused is that I have it set up the exact same way as what you showed in that example, except the thumbnails are stuck on the left side of the player.

**Comment by akashta** [comment]
You have to specify xywh param (x/y coordinates, width and height ) in the each vtt line. E.g.:
```
00:00.000 --> 00:05.000
http://nudality.com/vtt_001.jpg#xywh=0,0,200,150

00:05.000 --> 00:10.000
http://nudality.com/vtt_002.jpg#xywh=0,0,200,150
```
It's also recommended to group images like this:
http://hola.github.io/examples/cdn/thumb_1.jpg

The simplest way is to create an account on [holaspark.com](url) and use auto-generated thumbnails.

**Comment by shuaaaa** [comment]
OMG. I love you so, I can't thank you enough!

**Comment by shuaaaa** [comment]
Wait...

> It's also recommended to group images like this:
http://hola.github.io/examples/cdn/thumb_1.jpg

Why is that way better? Is there somewhere I can learn how to make those?

**Comment by akashta** [comment]
It will reduce the number of HTTP requests and make thumbnails work faster. I'm sorry but I can't help with thumbnails generating.

**Comment by shuaaaa** [comment]
Hey quick question. 

I've figured everything out for the sprites except how to get the player to read them properly. I think it has to do with this? 

```
        thumbnails: {
          0: {
            src: cdn_static+'/mp4/tears_of_steel_thumbnails_0_7.jpg',
            sprites: {
              width: 192,
              height: 80,
              position: [0, 87, 130, 172, 217, 240, 303, 346]
            }
          },
          389: {
            src: cdn_static+'/mp4/tears_of_steel_thumbnails_8_15.jpg',
            sprites: {
              width: 192,
              height: 80,
              position: [389, 431, 473, 517, 559, 603, 647, 690]
            }
          }
        },
```

Could you please help me understand what "position" and "380:" means? 

Thank you!
