### ISSUE TITLE
IMA SDK Hola Player Error

### ISSUE THREAD

**Issue by qya** [hola/hola_player#31]
```
Not allowed to load local resource: file://%22%22+%27+a+%27+%22//%22
'+X(a.Ue)+' Failed to load resource: the server responded with a status of 404 (Not Found)
'+X(a.url)+' Failed to load resource: the server responded with a status of 404 (Not Found)
bridge3.184.2_en.html:819 Uncaught ReferenceError: ima is not defined
    at bridge3.184.2_en.html:819
```
This problem hasbeen fixed ?

**Comment by akashta** [comment]
How to reproduce it? Could you please provide an example?

**Comment by qya** [comment]
![image](https://user-images.githubusercontent.com/32726692/32725691-a92f4e9c-c8a8-11e7-885a-79cd34a801cb.png)
Just see example 
@akashta http://hola.github.io/examples/cdn/#hola_player_ima

**Comment by akashta** [comment]
This example works fine for me. Do you use adblock? What browser is it?

**Comment by qya** [comment]
Im using 
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.102 Safari/537.36 Vivaldi/1.93.955.48
No adblock active + clean browser

**Comment by akashta** [comment]
Just checked it with the same browser (Vivaldi/1.93.955.48) and it's working fine. Looks like something is blocking ads on your side. Can you check on another browser/computer?

**Comment by qya** [comment]
@akashta 
Problem fixed this problem happened bcz my configuration cache not setup correcty
Issue closed :+1:
