### ISSUE TITLE
Include video.js license

### ISSUE THREAD

**Issue by abumalick** [hola/hola_player#37]
Hello,
I see that you changed the license of video.js https://github.com/hola/hola_player/commits/master/LICENSE

Did you read the terms of that license ? You are supposed to Include the original copyright and the full text of license in modified software.

http://www.apache.org/licenses/LICENSE-2.0
https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

**Comment by akashta** [comment]
Hi,
thanks for pointing it out, we will check and fix it according to the requirements

**Comment by akashta** [comment]
Hola Player includes video.js as dependency together with a lot of other modules, and our video.js fork has the correct license https://github.com/hola/video.js/blob/master/LICENSE

Our dist file contains video.js copyright and license as well:
https://github.com/hola/hola_player/blob/v1.0.119/dist/hola_player.dev.js

**Comment by abumalick** [comment]
Great, thank you for clarification.

Happy to know that you respect the license!

On Dec 6, 2017 18:00, "Andrey Kashta" <notifications@github.com> wrote:

Hola Player includes video.js as dependency together with a lot of other
modules, and our video.js fork has the correct license
https://github.com/hola/video.js/blob/master/LICENSE

Our dist file contains video.js copyright and license as well:
https://github.com/hola/hola_player/blob/v1.0.119/dist/hola_player.dev.js

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hola/hola_player/issues/37#issuecomment-349723646>, or mute
the thread
