### ISSUE TITLE
Starting loading before play.

### ISSUE THREAD

**Issue by mahmutbayri** [hola/hola_player#7]
Hi.

Before i used videojs5-hlsjs-source-handler to play hls video with hls.js plugin. New version was fixed, it does not load video playlist, chunklist, ts files before playing ( [commit details](https://github.com/streamroot/videojs5-hlsjs-source-handler/commit/0f3469702d03477410e87684592236c4a2e81738) ).

When i test hola player at http://hola.github.io/examples/cdn/#hola_player_hls_cdn , i see the same problem. It also would be nice to implement to hola player. If a page has more than one video player without autoplay, downloads unnecessary files may not be played.

Thanks.

**Comment by akashta** [comment]
Hi,

Implemented in 1.0.29. 
This might affect start time performance, so I made this behaviour configurable.
If preload option is set to 'none', player won't start loading hls video before play :
```window.hola_player({preload: 'none'});```
or 
```<video preload="none"```

**Comment by mahmutbayri** [comment]
It works now. Player starts with autoplay parameter in video pages, and preload might not affect start time performance.

In pages that have multiple embed videos, preloading causes bandwidth and unusing file request request (m3u8 file,  m3u8 chunklisk and ts files) in especially mobile devices, and this affects page loading time. Page loading time is very important for seo.

Thanks

**Comment by akashta** [comment]
Has this fix solved the issue, or anything else left? Can we close it?
