### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by praveenkumar8699** [hola/hola_player#8]
How to add responsiveness to the player?

**Comment by akashta** [comment]
What exactly do you mean? Could you please provide an example?

**Comment by praveenkumar8699** [comment]
Its like when the browser window size is reduced then the player should adapt to the window size 
Example check out this player on webpage try reducing the browser window size and see how the player automatically changes and adjusts

**Comment by akashta** [comment]
You can set videojs fluid option:
window.hola_player({videojs_options: {fluid: true}});

**Comment by akashta** [comment]
> This player is supported on all mobiles/pc/tablet's and other major browsers right.

Yes

**Comment by praveenkumar8699** [comment]
How to Set the Default Source label when the player loads for example
<source src="some1080psource" type="video/mp4" label="1080p">
<source src="some720psource" type="video/mp4" label="720p">

I want the player to choose the 720p source by default ... is there any way to do that?

**Comment by akashta** [comment]
Just add default attribute:
```<source src="some720psource" type="video/mp4" label="720p" default>```

**Comment by praveenkumar8699** [comment]
> <source src="some720psource" type="video/mp4" label="720p" default>

its not working...

**Comment by akashta** [comment]
try to clear localStorage or load the page in the incognito mode. Probably player keeps previously selected value.

**Comment by praveenkumar8699** [comment]
That's a bummer is there any documentation for holaplayer i can refer to? setting the video source dynamically using js

**Comment by akashta** [comment]
Can you create an example on jsbin.com, where I can reproduce this problem?
`hola_player` function returns instance of the videojs Player class. There is videojs documentation:
http://docs.videojs.com/docs/api/player.html#Methodssrc

**Comment by praveenkumar8699** [comment]
Here it is
http://jsbin.com/yujexutoqi/edit?console,output

**Comment by akashta** [comment]
It works fine for me. 720p/1080p is selected according to the `default` attribute

**Comment by praveenkumar8699** [comment]
For the first time it works. Select 1080p when the page loads then reload the entire webpage you will see 1080p selected not 720p

**Comment by akashta** [comment]
yes, because manually selected value has priority over default value. User selected quality is stored in `localStorage.vjs5_quality`

**Comment by praveenkumar8699** [comment]
is there Any way to prevent that storage?

**Comment by akashta** [comment]
try to add `prevent-default` attribute to the each source

**Comment by praveenkumar8699** [comment]
Thank You

**Comment by sajadzangene** [comment]
window.hola_player({videojs_options: {fluid: true}});

1. where should I add this code?
2. how should I make it width 100%?
thanks
