### ISSUE TITLE
Syntax problem on 1.0.30 version.

### ISSUE THREAD

**Issue by mahmutbayri** [hola/hola_player#9]
Hi,
There is an error on cdn.jsdelivr.net/hola_player/1.0.30/hola_player.js file. It wasn't compiled correctly. The file ends with "{if(!(a instanceof b))throw new TypeError("Cannot call a"

Thanks.

**Comment by akashta** [comment]
Hi, thanks for reporting this.
In npm repository file is correct. 
jsDelivr uses multiple CDN providers and looks like one of them has broken file. We are investigating this issue.
